Weight = float(input("Enter your weight Kg???: "))
Height = float(input("Enter your height Meter???: "))
BMI = float(Weight / (Height * 2))
if BMI > 40: print("Beo Phi cap do III")
elif 35 <= BMI < 40: print("Beo Phi cap do II")
elif 30 <= BMI < 35: print("Beo Phi cap do I")
elif 25 <= BMI < 30: print("Thua can")
elif 18.5 <= BMI < 25: print("Binh thuong")
elif 17 <= BMI < 18.5: print("Gay cap do I")
elif 16 <= BMI < 17: print("Gay cap do II")
else: print("Gay cap do III")